# Generated by Django 4.0.1 on 2022-01-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='conversation',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='discount',
            new_name='discount_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='operator',
            new_name='operator_id',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='chat',
            new_name='chat_id',
        ),
    ]
