# Generated by Django 4.0.1 on 2022-01-16 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='payload',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='Invalid payload', message='Payload had invalid characters', regex='^[a-zA-Z0-9{}$%_-\\/~@#$%^&()!?]$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Invalid phone', message='please enter phonenumber in the format +123123123, upto 15 digits allowed!', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Invalid phone', message='please enter phonenumber in the format +123123123, upto 15 digits allowed!', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
