# Generated by Django 4.0.1 on 2022-01-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chat_payload_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SENT', 'SENT')], default='NEW', max_length=32),
        ),
    ]
